neoforge_version=21.9.16-beta
packs=hud-legacy,id-location,canvas-graphics,tooltip-graphics,screen-contents,input-event,mount-horse,loot-container,contents-component,gamemode-legacy,stored-stacks,world-flags
label=1.21.9-1.21.10
range=[1.21.9,1.21.11)
neoforge_range=[21.9,21.11)
java=21
