neoforge_version=21.7.25-beta
packs=hud-legacy,id-location,canvas-graphics,tooltip-graphics,screen-contents,input-legacy,mount-horse,loot-container,contents-component,gamemode-legacy,stored-stacks,world-flags,stack-components,options-list,button-sprite,lootable-interface
label=1.21.7
range=[1.21.7]
neoforge_range=[21.7,21.8)
java=21
