neoforge_version=21.3.97
packs=hud-legacy,id-location,canvas-pose,tooltip-graphics,screen-render,input-legacy,mount-saddle,loot-container,contents-shulker,gamemode-legacy,stored-stacks,world-flags
label=1.21.3
range=[1.21.3]
neoforge_range=[21.3,21.4)
java=21
