neoforge_version=21.8.54
packs=hud-legacy,id-location,canvas-graphics,tooltip-graphics,screen-contents,input-legacy,mount-horse,loot-container,contents-component,gamemode-legacy,stored-stacks,world-flags
label=1.21.8
range=[1.21.8]
neoforge_range=[21.8,21.9)
java=21
