neoforge_version=21.10.64
packs=hud-legacy,id-location,canvas-graphics,tooltip-graphics,screen-contents,input-event,mount-horse,loot-container,contents-component,gamemode-legacy,stored-stacks,world-flags
label=1.21.10
range=[1.21.10]
neoforge_range=[21.10,21.11)
java=21
