neoforge_version=21.1.251
packs=hud-legacy,id-location,canvas-pose,tooltip-legacy,screen-render,input-legacy,mount-saddle,loot-legacy,contents-shulker,gamemode-legacy,stored-stacks,world-rules,stack-components,options-list,button-sprite,lootable-interface
label=1.21.1
range=[1.21.1]
neoforge_range=[21.1,21.2)
java=21
