neoforge_version=21.6.20-beta
packs=hud-legacy,id-location,canvas-graphics,tooltip-graphics,screen-contents,input-legacy,mount-horse,loot-container,contents-component,gamemode-legacy,stored-stacks,world-flags,stack-components,options-list,button-sprite,lootable-interface
label=1.21.6-1.21.8
range=[1.21.6,1.21.9)
neoforge_range=[21.6,21.9)
java=21
