neoforge_version=26.2.0.88
packs=hud-modern,id-identifier,canvas-extractor,tooltip-extractor,screen-extract,input-event,mount-menu,loot-container,contents-component,gamemode-modern,stored-templates,world-difficulty
label=26.2
range=[26.2,26.3)
neoforge_range=[26.2,26.3)
java=25
