neoforge_version=26.3.0.8-beta
packs=hud-modern,id-identifier,canvas-extractor,tooltip-extractor,screen-extract,input-event,mount-menu,loot-container,contents-component,gamemode-modern,stored-templates,world-difficulty
label=26.3
range=[26.3,26.4)
neoforge_range=[26.3,26.4)
java=25
