fabric_api_version=0.77.0+1.18.2
modmenu_version=3.2.5
packs=hud-legacy,id-constructor,canvas-1192,tooltip-1192,screen-render-1192,input-legacy,fabric-hud-callback,fabric-tooltip-component,mount-armor,loot-118,contents-nbt,gamemode-118,world-118,stack-nbt,options-grid-1192,button-texture-1192,lootable-nbt,settings-screen-1192,widgets-1192,registries-legacy,text-components-118,server-118
label=1.18.2
range=>=1.18.2 <1.19
java=17
gametest=false
