fabric_api_version=0.77.0+1.19.2
modmenu_version=4.1.2
packs=hud-legacy,id-constructor,canvas-1192,tooltip-1192,screen-render-1192,input-legacy,fabric-hud-callback,fabric-tooltip-component,mount-armor,loot-legacy,contents-nbt,gamemode-legacy,world-1192,stack-nbt,options-grid-1192,button-texture-1192,lootable-nbt,settings-screen-1192,widgets-1192,registries-legacy,text-components,server-119
label=1.19.2
range=>=1.19.2 <1.19.3
java=17
gametest=false
