fabric_api_version=0.97.3+1.20.4
modmenu_version=9.2.0
packs=hud-legacy,id-constructor,canvas-pose,tooltip-legacy,screen-render,input-legacy,fabric-hud-callback,fabric-tooltip-component,mount-armor,loot-legacy,contents-nbt,gamemode-legacy,world-rules,stack-nbt,options-grid-modern,button-texture,lootable-nbt,settings-screen,widgets,registries-builtin,text-components,server-119
label=1.20.2-1.20.4
range=>=1.20.2 <1.20.5
java=17
gametest=false
