fabric_api_version=0.116.17+1.21.1
modmenu_version=11.0.4
packs=hud-legacy,id-location,canvas-pose,tooltip-legacy,screen-render,input-legacy,fabric-hud-callback,fabric-tooltip-component,mount-saddle,loot-legacy,contents-shulker,gamemode-legacy,stored-stacks,world-rules
label=1.21.1
range=1.21.1
java=21
gametest=false
