fabric_api_version=0.119.4+1.21.4
modmenu_version=13.0.4
packs=hud-legacy,id-location,canvas-pose,tooltip-graphics,screen-render,input-legacy,fabric-hud-callback,fabric-tooltip-component,mount-saddle,loot-container,contents-shulker,gamemode-legacy,stored-stacks,world-flags
label=1.21.4
range=1.21.4
java=21
