fabric_api_version=0.129.0+1.21.7
modmenu_version=15.0.2
packs=hud-legacy,id-location,canvas-graphics,tooltip-graphics,screen-contents,input-legacy,fabric-hud-element,fabric-tooltip-component,mount-horse,loot-container,contents-component,gamemode-legacy,stored-stacks,world-flags,stack-components,options-list,button-sprite,lootable-interface
label=1.21.7
range=1.21.7
java=21
