fabric_api_version=0.155.3+26.1.2
modmenu_version=18.0.1
packs=hud-legacy,id-identifier,canvas-extractor,tooltip-extractor,screen-extract,input-event,fabric-hud-element,fabric-tooltip-client,mount-menu,loot-container,contents-component,gamemode-modern,stored-templates,world-difficulty,stack-components,options-list,button-sprite,lootable-interface
label=26.1-26.1.2
range=>=26.1 <26.2
java=25
