fabric_api_version=0.161.0+26.3
modmenu_version=20.0.1
packs=hud-modern,id-identifier,canvas-extractor,tooltip-extractor,screen-extract,input-event,fabric-hud-element,fabric-tooltip-client,mount-menu,loot-container,contents-component,gamemode-modern,stored-templates,world-difficulty,stack-components,options-list,button-sprite,lootable-interface
label=26.3
range=>=26.3 <26.4
java=25
