minecraft=26.4-snapshot-1
fabric_api_version=0.161.1+26.4
modmenu_version=20.0.1
packs=hud-modern,id-identifier,canvas-extractor,tooltip-extractor,screen-extract,input-event,fabric-hud-element,fabric-tooltip-client,mount-menu,loot-container,contents-component,gamemode-modern,stored-templates,world-difficulty
label=26.4-snapshot-1
range=>=26.4- <26.5-
java=25
