forge_version=1.16.5-36.2.42
packs=hud-legacy,id-constructor,canvas-1192,tooltip-116,screen-render-1192,input-116,mount-armor,loot-116,contents-nbt,gamemode-116,world-116,stack-nbt-116,options-grid-116,button-texture-116,lootable-116,settings-screen-1192,widgets-1192,registries-legacy,text-components-118,server-116,screen-116,forge-client-116
label=1.16.5
range=[1.16.5,1.17)
forge_range=[36,)
loader_range=[36,)
pack_format=6
java=8
main_excludes=dev/lidless/mixin/ItemStackMixin.java,dev/lidless/tooltip/ContainerPreview.java,dev/lidless/mixin/AbstractContainerScreenMixin.java
