forge_version=1.19.2-43.5.2
packs=hud-legacy,id-constructor,canvas-1192,tooltip-1192,screen-render-1192,input-legacy,mount-armor,loot-legacy,contents-nbt,gamemode-legacy,world-1192,stack-nbt,options-grid-1192,button-texture-1192,lootable-nbt,settings-screen-1192,widgets-1192,registries-legacy,text-components,server-119,forge-client
label=1.19.2
range=[1.19.2,1.19.3)
forge_range=[43,)
loader_range=[43,)
pack_format=9
java=17
