forge_version=1.20.1-47.4.23
packs=hud-legacy,id-constructor,canvas-pose,tooltip-legacy,screen-render,input-legacy,mount-armor,loot-legacy,contents-nbt,gamemode-legacy,world-legacy,stack-nbt,options-grid,button-texture,lootable-nbt
label=1.20.1
range=[1.20.1,1.20.2)
forge_range=[47,)
java=17
